//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UndertaleModTool.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UndertaleModTool.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 _About 的本地化字符串。
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Actions 的本地化字符串。
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Active targets 的本地化字符串。
        /// </summary>
        public static string Active_targets {
            get {
                return ResourceManager.GetString("Active_targets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add 的本地化字符串。
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add in place (unimplemented) 的本地化字符串。
        /// </summary>
        public static string Add_in_place__unimplemented {
            get {
                return ResourceManager.GetString("Add_in_place__unimplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add new extension option 的本地化字符串。
        /// </summary>
        public static string Add_new_extension_option {
            get {
                return ResourceManager.GetString("Add_new_extension_option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add the new room to the end of the room order list? 的本地化字符串。
        /// </summary>
        public static string Add_the_new_room_to_the_end_of_the {
            get {
                return ResourceManager.GetString("Add_the_new_room_to_the_end_of_the", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add to room order list 的本地化字符串。
        /// </summary>
        public static string Add_to_room_order_list {
            get {
                return ResourceManager.GetString("Add_to_room_order_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Additive color blend 的本地化字符串。
        /// </summary>
        public static string Additive_color_blend {
            get {
                return ResourceManager.GetString("Additive_color_blend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Allow statistics 的本地化字符串。
        /// </summary>
        public static string Allow_statistics {
            get {
                return ResourceManager.GetString("Allow_statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An error occurred while trying to load:\n{0} 的本地化字符串。
        /// </summary>
        public static string An_error_occurred_while_trying_to {
            get {
                return ResourceManager.GetString("An_error_occurred_while_trying_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Angular damping 的本地化字符串。
        /// </summary>
        public static string Angular_damping {
            get {
                return ResourceManager.GetString("Angular_damping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Animate sprite 的本地化字符串。
        /// </summary>
        public static string Animate_sprite {
            get {
                return ResourceManager.GetString("Animate_sprite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Argument Types 的本地化字符串。
        /// </summary>
        public static string Argument_Types {
            get {
                return ResourceManager.GetString("Argument_Types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Arguments count 的本地化字符串。
        /// </summary>
        public static string Arguments_count {
            get {
                return ResourceManager.GetString("Arguments_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Audio file 的本地化字符串。
        /// </summary>
        public static string Audio_file {
            get {
                return ResourceManager.GetString("Audio_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Audio group 的本地化字符串。
        /// </summary>
        public static string Audio_group {
            get {
                return ResourceManager.GetString("Audio_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Audio groups 的本地化字符串。
        /// </summary>
        public static string Audio_groups {
            get {
                return ResourceManager.GetString("Audio_groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Backgrounds &amp; Tile sets 的本地化字符串。
        /// </summary>
        public static string Backgrounds___Tile_sets {
            get {
                return ResourceManager.GetString("Backgrounds___Tile_sets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Backgrounds &amp; Tile sets 的本地化字符串。
        /// </summary>
        public static string Backgrounds__amp__Tile_sets {
            get {
                return ResourceManager.GetString("Backgrounds__amp__Tile_sets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bottom: 的本地化字符串。
        /// </summary>
        public static string Bottom {
            get {
                return ResourceManager.GetString("Bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bounding box mode 的本地化字符串。
        /// </summary>
        public static string Bounding_box_mode {
            get {
                return ResourceManager.GetString("Bounding_box_mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bounding size 的本地化字符串。
        /// </summary>
        public static string Bounding_size {
            get {
                return ResourceManager.GetString("Bounding_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bytecode version 的本地化字符串。
        /// </summary>
        public static string Bytecode_version {
            get {
                return ResourceManager.GetString("Bytecode_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot select the code editor mode tab - the instance is not found. 的本地化字符串。
        /// </summary>
        public static string Cannot_select_the_code_editor_mode {
            get {
                return ResourceManager.GetString("Cannot_select_the_code_editor_mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check your internet connection. 的本地化字符串。
        /// </summary>
        public static string Check_your_internet_connection {
            get {
                return ResourceManager.GetString("Check_your_internet_connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Class Name 的本地化字符串。
        /// </summary>
        public static string Class_Name {
            get {
                return ResourceManager.GetString("Class_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cleanup function name 的本地化字符串。
        /// </summary>
        public static string Cleanup_function_name {
            get {
                return ResourceManager.GetString("Cleanup_function_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Close 的本地化字符串。
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close all tabs 的本地化字符串。
        /// </summary>
        public static string Close_all_tabs {
            get {
                return ResourceManager.GetString("Close_all_tabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close current tab 的本地化字符串。
        /// </summary>
        public static string Close_current_tab {
            get {
                return ResourceManager.GetString("Close_current_tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Closed 的本地化字符串。
        /// </summary>
        public static string Closed {
            get {
                return ResourceManager.GetString("Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Code 的本地化字符串。
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Code locals 的本地化字符串。
        /// </summary>
        public static string Code_locals {
            get {
                return ResourceManager.GetString("Code_locals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Collision masks 的本地化字符串。
        /// </summary>
        public static string Collision_masks {
            get {
                return ResourceManager.GetString("Collision_masks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Collision shape 的本地化字符串。
        /// </summary>
        public static string Collision_shape {
            get {
                return ResourceManager.GetString("Collision_shape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (CollisionMask) 的本地化字符串。
        /// </summary>
        public static string CollisionMask {
            get {
                return ResourceManager.GetString("CollisionMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Config 的本地化字符串。
        /// </summary>
        public static string Config {
            get {
                return ResourceManager.GetString("Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Content 的本地化字符串。
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy name to clipboard 的本地化字符串。
        /// </summary>
        public static string Copy_name_to_clipboard {
            get {
                return ResourceManager.GetString("Copy_name_to_clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create 的本地化字符串。
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create new code entry 的本地化字符串。
        /// </summary>
        public static string Create_new_code_entry {
            get {
                return ResourceManager.GetString("Create_new_code_entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data 的本地化字符串。
        /// </summary>
        public static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Debugger port 的本地化字符串。
        /// </summary>
        public static string Debugger_port {
            get {
                return ResourceManager.GetString("Debugger_port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Decompiled 的本地化字符串。
        /// </summary>
        public static string Decompiled {
            get {
                return ResourceManager.GetString("Decompiled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default window size 的本地化字符串。
        /// </summary>
        public static string Default_window_size {
            get {
                return ResourceManager.GetString("Default_window_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delay measured in: 的本地化字符串。
        /// </summary>
        public static string Delay_measured_in {
            get {
                return ResourceManager.GetString("Delay_measured_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delay min|max 的本地化字符串。
        /// </summary>
        public static string Delay_min_max {
            get {
                return ResourceManager.GetString("Delay_min_max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        public static string Delete1 {
            get {
                return ResourceManager.GetString("Delete1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Density 的本地化字符串。
        /// </summary>
        public static string Density {
            get {
                return ResourceManager.GetString("Density", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Depth 的本地化字符串。
        /// </summary>
        public static string Depth {
            get {
                return ResourceManager.GetString("Depth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Direction increase|wiggle 的本地化字符串。
        /// </summary>
        public static string Direction_increase_wiggle {
            get {
                return ResourceManager.GetString("Direction_increase_wiggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Direction min|max 的本地化字符串。
        /// </summary>
        public static string Direction_min_max {
            get {
                return ResourceManager.GetString("Direction_min_max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DirectPlay GUID 的本地化字符串。
        /// </summary>
        public static string DirectPlay_GUID {
            get {
                return ResourceManager.GetString("DirectPlay_GUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disable GMS debugger 的本地化字符串。
        /// </summary>
        public static string Disable_GMS_debugger {
            get {
                return ResourceManager.GetString("Disable_GMS_debugger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disassembly 的本地化字符串。
        /// </summary>
        public static string Disassembly {
            get {
                return ResourceManager.GetString("Disassembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Display name 的本地化字符串。
        /// </summary>
        public static string Display_name {
            get {
                return ResourceManager.GetString("Display_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Distribution 的本地化字符串。
        /// </summary>
        public static string Distribution {
            get {
                return ResourceManager.GetString("Distribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Double click on the items on the left to view them! 的本地化字符串。
        /// </summary>
        public static string Double_click_on_the_items_on_the {
            get {
                return ResourceManager.GetString("Double_click_on_the_items_on_the", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Double click to add 的本地化字符串。
        /// </summary>
        public static string Double_click_to_add {
            get {
                return ResourceManager.GetString("Double_click_to_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Downloading 的本地化字符串。
        /// </summary>
        public static string Downloading {
            get {
                return ResourceManager.GetString("Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Downloading new version... 的本地化字符串。
        /// </summary>
        public static string Downloading_new_version {
            get {
                return ResourceManager.GetString("Downloading_new_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Draw order 的本地化字符串。
        /// </summary>
        public static string Draw_order {
            get {
                return ResourceManager.GetString("Draw_order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Effects 的本地化字符串。
        /// </summary>
        public static string Effects {
            get {
                return ResourceManager.GetString("Effects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Embedded audio 的本地化字符串。
        /// </summary>
        public static string Embedded_audio {
            get {
                return ResourceManager.GetString("Embedded_audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Embedded images 的本地化字符串。
        /// </summary>
        public static string Embedded_images {
            get {
                return ResourceManager.GetString("Embedded_images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Embedded textures 的本地化字符串。
        /// </summary>
        public static string Embedded_textures {
            get {
                return ResourceManager.GetString("Embedded_textures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Emit count 的本地化字符串。
        /// </summary>
        public static string Emit_count {
            get {
                return ResourceManager.GetString("Emit_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Emit mode 的本地化字符串。
        /// </summary>
        public static string Emit_mode {
            get {
                return ResourceManager.GetString("Emit_mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Emit relative 的本地化字符串。
        /// </summary>
        public static string Emit_relative {
            get {
                return ResourceManager.GetString("Emit_relative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Emitters 的本地化字符串。
        /// </summary>
        public static string Emitters {
            get {
                return ResourceManager.GetString("Emitters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enabled 的本地化字符串。
        /// </summary>
        public static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 End color 的本地化字符串。
        /// </summary>
        public static string End_color {
            get {
                return ResourceManager.GetString("End_color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (error message is missing) 的本地化字符串。
        /// </summary>
        public static string error_message_is_missing {
            get {
                return ResourceManager.GetString("error_message_is_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Errors occurred during loading. High chance of data loss! Proceed at your own risk. 的本地化字符串。
        /// </summary>
        public static string Errors_occurred_during_loading__High {
            get {
                return ResourceManager.GetString("Errors_occurred_during_loading__High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Events 的本地化字符串。
        /// </summary>
        public static string Events {
            get {
                return ResourceManager.GetString("Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export 的本地化字符串。
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export all frames (or Spine data if this is a Spine sprite) 的本地化字符串。
        /// </summary>
        public static string Export_all_frames__or_Spine_data {
            get {
                return ResourceManager.GetString("Export_all_frames__or_Spine_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export mask 的本地化字符串。
        /// </summary>
        public static string Export_mask {
            get {
                return ResourceManager.GetString("Export_mask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exported Sprite Index 的本地化字符串。
        /// </summary>
        public static string Exported_Sprite_Index {
            get {
                return ResourceManager.GetString("Exported_Sprite_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extensions 的本地化字符串。
        /// </summary>
        public static string Extensions {
            get {
                return ResourceManager.GetString("Extensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 External Name 的本地化字符串。
        /// </summary>
        public static string External_Name {
            get {
                return ResourceManager.GetString("External_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _File 的本地化字符串。
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File associations 的本地化字符串。
        /// </summary>
        public static string File_associations {
            get {
                return ResourceManager.GetString("File_associations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File 的本地化字符串。
        /// </summary>
        public static string File1 {
            get {
                return ResourceManager.GetString("File1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FileName 的本地化字符串。
        /// </summary>
        public static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Files 的本地化字符串。
        /// </summary>
        public static string Files {
            get {
                return ResourceManager.GetString("Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Filter by name... 的本地化字符串。
        /// </summary>
        public static string Filter_by_name {
            get {
                return ResourceManager.GetString("Filter_by_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Find 的本地化字符串。
        /// </summary>
        public static string Find {
            get {
                return ResourceManager.GetString("Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Find all references 的本地化字符串。
        /// </summary>
        public static string Find_all_references {
            get {
                return ResourceManager.GetString("Find_all_references", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Find all references to this page item 的本地化字符串。
        /// </summary>
        public static string Find_all_references_to_this_page {
            get {
                return ResourceManager.GetString("Find_all_references_to_this_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Find unreferenced _assets 的本地化字符串。
        /// </summary>
        public static string Find_unreferenced__assets {
            get {
                return ResourceManager.GetString("Find_unreferenced__assets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 First-time setup: Would you like to associate GameMaker data files (like .win) with UndertaleModTool? 的本地化字符串。
        /// </summary>
        public static string First_time_setup__Would_you_like {
            get {
                return ResourceManager.GetString("First_time_setup__Would_you_like", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Flags 的本地化字符串。
        /// </summary>
        public static string Flags {
            get {
                return ResourceManager.GetString("Flags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fonts 的本地化字符串。
        /// </summary>
        public static string Fonts {
            get {
                return ResourceManager.GetString("Fonts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Forward 的本地化字符串。
        /// </summary>
        public static string Forward {
            get {
                return ResourceManager.GetString("Forward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FPS 的本地化字符串。
        /// </summary>
        public static string FPS {
            get {
                return ResourceManager.GetString("FPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Frame Time (microseconds) 的本地化字符串。
        /// </summary>
        public static string Frame_Time__microseconds {
            get {
                return ResourceManager.GetString("Frame_Time__microseconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Friction 的本地化字符串。
        /// </summary>
        public static string Friction {
            get {
                return ResourceManager.GetString("Friction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Function classifications 的本地化字符串。
        /// </summary>
        public static string Function_classifications {
            get {
                return ResourceManager.GetString("Function_classifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Functions 的本地化字符串。
        /// </summary>
        public static string Functions {
            get {
                return ResourceManager.GetString("Functions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Game End scripts 的本地化字符串。
        /// </summary>
        public static string Game_End_scripts {
            get {
                return ResourceManager.GetString("Game_End_scripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Game GUID 的本地化字符串。
        /// </summary>
        public static string Game_GUID {
            get {
                return ResourceManager.GetString("Game_GUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Game ID 的本地化字符串。
        /// </summary>
        public static string Game_ID {
            get {
                return ResourceManager.GetString("Game_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Game objects 的本地化字符串。
        /// </summary>
        public static string Game_objects {
            get {
                return ResourceManager.GetString("Game_objects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 General info 的本地化字符串。
        /// </summary>
        public static string General_info {
            get {
                return ResourceManager.GetString("General_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Generate o_ffset map 的本地化字符串。
        /// </summary>
        public static string Generate_o_ffset_map {
            get {
                return ResourceManager.GetString("Generate_o_ffset_map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Generated mips 的本地化字符串。
        /// </summary>
        public static string Generated_mips {
            get {
                return ResourceManager.GetString("Generated_mips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Generating debugger data... 的本地化字符串。
        /// </summary>
        public static string Generating_debugger_data {
            get {
                return ResourceManager.GetString("Generating_debugger_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _GitHub 的本地化字符串。
        /// </summary>
        public static string GitHub {
            get {
                return ResourceManager.GetString("GitHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Global init 的本地化字符串。
        /// </summary>
        public static string Global_init {
            get {
                return ResourceManager.GetString("Global_init", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Global initialization scripts 的本地化字符串。
        /// </summary>
        public static string Global_initialization_scripts {
            get {
                return ResourceManager.GetString("Global_initialization_scripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GLSL ES fragment source 的本地化字符串。
        /// </summary>
        public static string GLSL_ES_fragment_source {
            get {
                return ResourceManager.GetString("GLSL_ES_fragment_source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GLSL ES vertex source 的本地化字符串。
        /// </summary>
        public static string GLSL_ES_vertex_source {
            get {
                return ResourceManager.GetString("GLSL_ES_vertex_source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GLSL fragment source 的本地化字符串。
        /// </summary>
        public static string GLSL_fragment_source {
            get {
                return ResourceManager.GetString("GLSL_fragment_source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GLSL vertex source 的本地化字符串。
        /// </summary>
        public static string GLSL_vertex_source {
            get {
                return ResourceManager.GetString("GLSL_vertex_source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GMS Debugger 的本地化字符串。
        /// </summary>
        public static string GMS_Debugger {
            get {
                return ResourceManager.GetString("GMS_Debugger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gravity force|direction 的本地化字符串。
        /// </summary>
        public static string Gravity_force_direction {
            get {
                return ResourceManager.GetString("Gravity_force_direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Group 的本地化字符串。
        /// </summary>
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Group Name 的本地化字符串。
        /// </summary>
        public static string Group_Name {
            get {
                return ResourceManager.GetString("Group_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Height: 的本地化字符串。
        /// </summary>
        public static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Help 的本地化字符串。
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hint: Prior to GM 2023.8, these &quot;Size&quot; values were not split by x and y.
        ///UndertaleModTool represents this by averaging the values.
        ///For best results, enter the same value in both fields. 的本地化字符串。
        /// </summary>
        public static string Hint__Prior_to_GM_2023_8__these {
            get {
                return ResourceManager.GetString("Hint__Prior_to_GM_2023_8__these", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hint: This image is mouse interactable (3 mouse buttons and mouse wheel). 的本地化字符串。
        /// </summary>
        public static string Hint__This_image_is_mouse_interactable {
            get {
                return ResourceManager.GetString("Hint__This_image_is_mouse_interactable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hint: You can click on any tile region below to highlight its ID above. 的本地化字符串。
        /// </summary>
        public static string Hint__You_can_click_on_any_tile_region {
            get {
                return ResourceManager.GetString("Hint__You_can_click_on_any_tile_region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HLSL9 fragment source 的本地化字符串。
        /// </summary>
        public static string HLSL9_fragment_source {
            get {
                return ResourceManager.GetString("HLSL9_fragment_source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HLSL9 vertex source 的本地化字符串。
        /// </summary>
        public static string HLSL9_vertex_source {
            get {
                return ResourceManager.GetString("HLSL9_vertex_source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ID 的本地化字符串。
        /// </summary>
        public static string ID1 {
            get {
                return ResourceManager.GetString("ID1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import mask 的本地化字符串。
        /// </summary>
        public static string Import_mask {
            get {
                return ResourceManager.GetString("Import_mask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import 的本地化字符串。
        /// </summary>
        public static string Import1 {
            get {
                return ResourceManager.GetString("Import1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Init function name 的本地化字符串。
        /// </summary>
        public static string Init_function_name {
            get {
                return ResourceManager.GetString("Init_function_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Instance/global variable count 的本地化字符串。
        /// </summary>
        public static string Instance_global_variable_count {
            get {
                return ResourceManager.GetString("Instance_global_variable_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Instance/global variable count (again) 的本地化字符串。
        /// </summary>
        public static string Instance_global_variable_count__again {
            get {
                return ResourceManager.GetString("Instance_global_variable_count__again", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Instance type 的本地化字符串。
        /// </summary>
        public static string Instance_type {
            get {
                return ResourceManager.GetString("Instance_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Interval measured in: 的本地化字符串。
        /// </summary>
        public static string Interval_measured_in {
            get {
                return ResourceManager.GetString("Interval_measured_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Interval min|max 的本地化字符串。
        /// </summary>
        public static string Interval_min_max {
            get {
                return ResourceManager.GetString("Interval_min_max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid mask data! 的本地化字符串。
        /// </summary>
        public static string Invalid_mask_data {
            get {
                return ResourceManager.GetString("Invalid_mask_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid name 的本地化字符串。
        /// </summary>
        public static string Invalid_name {
            get {
                return ResourceManager.GetString("Invalid_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Is awake 的本地化字符串。
        /// </summary>
        public static string Is_awake {
            get {
                return ResourceManager.GetString("Is_awake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Is kinematic 的本地化字符串。
        /// </summary>
        public static string Is_kinematic {
            get {
                return ResourceManager.GetString("Is_kinematic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Is orientation relative 的本地化字符串。
        /// </summary>
        public static string Is_orientation_relative {
            get {
                return ResourceManager.GetString("Is_orientation_relative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Is sensor 的本地化字符串。
        /// </summary>
        public static string Is_sensor {
            get {
                return ResourceManager.GetString("Is_sensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Is special type? 的本地化字符串。
        /// </summary>
        public static string Is_special_type {
            get {
                return ResourceManager.GetString("Is_special_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Item name is null. 的本地化字符串。
        /// </summary>
        public static string Item_name_is_null {
            get {
                return ResourceManager.GetString("Item_name_is_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Items/frames per tile 的本地化字符串。
        /// </summary>
        public static string Items_frames_per_tile {
            get {
                return ResourceManager.GetString("Items_frames_per_tile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Kind 的本地化字符串。
        /// </summary>
        public static string Kind1 {
            get {
                return ResourceManager.GetString("Kind1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Last object ID 的本地化字符串。
        /// </summary>
        public static string Last_object_ID {
            get {
                return ResourceManager.GetString("Last_object_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Last tile ID 的本地化字符串。
        /// </summary>
        public static string Last_tile_ID {
            get {
                return ResourceManager.GetString("Last_tile_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Left: 的本地化字符串。
        /// </summary>
        public static string Left {
            get {
                return ResourceManager.GetString("Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 License CRC32 的本地化字符串。
        /// </summary>
        public static string License_CRC32 {
            get {
                return ResourceManager.GetString("License_CRC32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 License MD5 的本地化字符串。
        /// </summary>
        public static string License_MD5 {
            get {
                return ResourceManager.GetString("License_MD5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lifetime min|max 的本地化字符串。
        /// </summary>
        public static string Lifetime_min_max {
            get {
                return ResourceManager.GetString("Lifetime_min_max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Linear damping 的本地化字符串。
        /// </summary>
        public static string Linear_damping {
            get {
                return ResourceManager.GetString("Linear_damping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 List 的本地化字符串。
        /// </summary>
        public static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load_data_win_file_first 的本地化字符串。
        /// </summary>
        public static string Load_data_win_file_first {
            get {
                return ResourceManager.GetString("Load_data_win_file_first", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load error 的本地化字符串。
        /// </summary>
        public static string Load_error {
            get {
                return ResourceManager.GetString("Load_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (...loading...) 的本地化字符串。
        /// </summary>
        public static string loading {
            get {
                return ResourceManager.GetString("loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loading, please wait... 的本地化字符串。
        /// </summary>
        public static string Loading__please_wait {
            get {
                return ResourceManager.GetString("Loading__please_wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loading problems 的本地化字符串。
        /// </summary>
        public static string Loading_problems {
            get {
                return ResourceManager.GetString("Loading_problems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loading warning 的本地化字符串。
        /// </summary>
        public static string Loading_warning {
            get {
                return ResourceManager.GetString("Loading_warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loading 的本地化字符串。
        /// </summary>
        public static string Loading1 {
            get {
                return ResourceManager.GetString("Loading1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Local variables 的本地化字符串。
        /// </summary>
        public static string Local_variables {
            get {
                return ResourceManager.GetString("Local_variables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Locals count 的本地化字符串。
        /// </summary>
        public static string Locals_count {
            get {
                return ResourceManager.GetString("Locals_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Margin 的本地化字符串。
        /// </summary>
        public static string Margin {
            get {
                return ResourceManager.GetString("Margin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Max local variable count 的本地化字符串。
        /// </summary>
        public static string Max_local_variable_count {
            get {
                return ResourceManager.GetString("Max_local_variable_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Middle color 的本地化字符串。
        /// </summary>
        public static string Middle_color {
            get {
                return ResourceManager.GetString("Middle_color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Moments 的本地化字符串。
        /// </summary>
        public static string Moments {
            get {
                return ResourceManager.GetString("Moments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 n/a 的本地化字符串。
        /// </summary>
        public static string n_a {
            get {
                return ResourceManager.GetString("n_a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name string ID 的本地化字符串。
        /// </summary>
        public static string Name_string_ID {
            get {
                return ResourceManager.GetString("Name_string_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _New 的本地化字符串。
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New file created, have fun making a game out of nothing\nI TOLD YOU to open a data.win, not create a new file! :P 的本地化字符串。
        /// </summary>
        public static string New_file_created__have_fun_making {
            get {
                return ResourceManager.GetString("New_file_created__have_fun_making", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No game loaded 的本地化字符串。
        /// </summary>
        public static string No_game_loaded {
            get {
                return ResourceManager.GetString("No_game_loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (No scripts found!) 的本地化字符串。
        /// </summary>
        public static string No_scripts_found {
            get {
                return ResourceManager.GetString("No_scripts_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 None 的本地化字符串。
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (null) 的本地化字符串。
        /// </summary>
        public static string null1 {
            get {
                return ResourceManager.GetString("null1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Offset 的本地化字符串。
        /// </summary>
        public static string Offset {
            get {
                return ResourceManager.GetString("Offset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Open 的本地化字符串。
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open a data.win file to get started, then double click on the items on the left to view them. 的本地化字符串。
        /// </summary>
        public static string Open_a_data_win_file_to_get_started {
            get {
                return ResourceManager.GetString("Open_a_data_win_file_to_get_started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open in new tab 的本地化字符串。
        /// </summary>
        public static string Open_in_new_tab {
            get {
                return ResourceManager.GetString("Open_in_new_tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open referenced object 的本地化字符串。
        /// </summary>
        public static string Open_referenced_object {
            get {
                return ResourceManager.GetString("Open_referenced_object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Orientation increase|wiggle 的本地化字符串。
        /// </summary>
        public static string Orientation_increase_wiggle {
            get {
                return ResourceManager.GetString("Orientation_increase_wiggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Orientation min|max 的本地化字符串。
        /// </summary>
        public static string Orientation_min_max {
            get {
                return ResourceManager.GetString("Orientation_min_max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Origin 的本地化字符串。
        /// </summary>
        public static string Origin1 {
            get {
                return ResourceManager.GetString("Origin1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Output Border X 的本地化字符串。
        /// </summary>
        public static string Output_Border_X {
            get {
                return ResourceManager.GetString("Output_Border_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Output Border Y 的本地化字符串。
        /// </summary>
        public static string Output_Border_Y {
            get {
                return ResourceManager.GetString("Output_Border_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parent 的本地化字符串。
        /// </summary>
        public static string Parent {
            get {
                return ResourceManager.GetString("Parent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parent entry 的本地化字符串。
        /// </summary>
        public static string Parent_entry {
            get {
                return ResourceManager.GetString("Parent_entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Particle system emitters 的本地化字符串。
        /// </summary>
        public static string Particle_system_emitters {
            get {
                return ResourceManager.GetString("Particle_system_emitters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Particle systems 的本地化字符串。
        /// </summary>
        public static string Particle_systems {
            get {
                return ResourceManager.GetString("Particle_systems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Path (GM 2024.14+) 的本地化字符串。
        /// </summary>
        public static string Path__GM_2024_14 {
            get {
                return ResourceManager.GetString("Path__GM_2024_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Paths 的本地化字符串。
        /// </summary>
        public static string Paths {
            get {
                return ResourceManager.GetString("Paths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Persistent 的本地化字符串。
        /// </summary>
        public static string Persistent {
            get {
                return ResourceManager.GetString("Persistent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Physics 的本地化字符串。
        /// </summary>
        public static string Physics {
            get {
                return ResourceManager.GetString("Physics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Physics shape vertices 的本地化字符串。
        /// </summary>
        public static string Physics_shape_vertices {
            get {
                return ResourceManager.GetString("Physics_shape_vertices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pitch 的本地化字符串。
        /// </summary>
        public static string Pitch {
            get {
                return ResourceManager.GetString("Pitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Play 的本地化字符串。
        /// </summary>
        public static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Playback speed 的本地化字符串。
        /// </summary>
        public static string Playback_speed {
            get {
                return ResourceManager.GetString("Playback_speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Playback speed type 的本地化字符串。
        /// </summary>
        public static string Playback_speed_type {
            get {
                return ResourceManager.GetString("Playback_speed_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Points 的本地化字符串。
        /// </summary>
        public static string Points {
            get {
                return ResourceManager.GetString("Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Precision 的本地化字符串。
        /// </summary>
        public static string Precision {
            get {
                return ResourceManager.GetString("Precision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preload 的本地化字符串。
        /// </summary>
        public static string Preload {
            get {
                return ResourceManager.GetString("Preload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preload (old audio system) 的本地化字符串。
        /// </summary>
        public static string Preload__old_audio_system {
            get {
                return ResourceManager.GetString("Preload__old_audio_system", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Product ID 的本地化字符串。
        /// </summary>
        public static string Product_ID {
            get {
                return ResourceManager.GetString("Product_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Random 的本地化字符串。
        /// </summary>
        public static string Random {
            get {
                return ResourceManager.GetString("Random", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Region X|Y|Width|Height 的本地化字符串。
        /// </summary>
        public static string Region_X_Y_Width_Height {
            get {
                return ResourceManager.GetString("Region_X_Y_Width_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove reference 的本地化字符串。
        /// </summary>
        public static string Remove_reference {
            get {
                return ResourceManager.GetString("Remove_reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Restitution 的本地化字符串。
        /// </summary>
        public static string Restitution {
            get {
                return ResourceManager.GetString("Restitution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Restore last closed tab 的本地化字符串。
        /// </summary>
        public static string Restore_last_closed_tab {
            get {
                return ResourceManager.GetString("Restore_last_closed_tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Return Type 的本地化字符串。
        /// </summary>
        public static string Return_Type {
            get {
                return ResourceManager.GetString("Return_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Right: 的本地化字符串。
        /// </summary>
        public static string Right {
            get {
                return ResourceManager.GetString("Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Room order 的本地化字符串。
        /// </summary>
        public static string Room_order {
            get {
                return ResourceManager.GetString("Room_order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rooms 的本地化字符串。
        /// </summary>
        public static string Rooms {
            get {
                return ResourceManager.GetString("Rooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rotation 的本地化字符串。
        /// </summary>
        public static string Rotation {
            get {
                return ResourceManager.GetString("Rotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Run _other script... 的本地化字符串。
        /// </summary>
        public static string Run__other_script {
            get {
                return ResourceManager.GetString("Run__other_script", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Run game under GMS _debugger 的本地化字符串。
        /// </summary>
        public static string Run_game_under_GMS__debugger {
            get {
                return ResourceManager.GetString("Run_game_under_GMS__debugger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Run game with other runner 的本地化字符串。
        /// </summary>
        public static string Run_game_with_other_runner {
            get {
                return ResourceManager.GetString("Run_game_with_other_runner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Runner literally doesn&apos;t care about the &apos;Kind&apos; value.
        ///The &apos;ID&apos; does matter though, so make sure you don&apos;t have any overlaps. 的本地化字符串。
        /// </summary>
        public static string Runner_literally_doesn_t_care_about {
            get {
                return ResourceManager.GetString("Runner_literally_doesn_t_care_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 S_ettings 的本地化字符串。
        /// </summary>
        public static string S_ettings {
            get {
                return ResourceManager.GetString("S_ettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Save 的本地化字符串。
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save changes before quitting? 的本地化字符串。
        /// </summary>
        public static string Save_changes_before_quitting {
            get {
                return ResourceManager.GetString("Save_changes_before_quitting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Saving 的本地化字符串。
        /// </summary>
        public static string Saving {
            get {
                return ResourceManager.GetString("Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Saving, please wait... 的本地化字符串。
        /// </summary>
        public static string Saving__please_wait {
            get {
                return ResourceManager.GetString("Saving__please_wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scale 的本地化字符串。
        /// </summary>
        public static string Scale {
            get {
                return ResourceManager.GetString("Scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scale X|Y 的本地化字符串。
        /// </summary>
        public static string Scale_X_Y {
            get {
                return ResourceManager.GetString("Scale_X_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scaled 的本地化字符串。
        /// </summary>
        public static string Scaled {
            get {
                return ResourceManager.GetString("Scaled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Script error 的本地化字符串。
        /// </summary>
        public static string Script_error {
            get {
                return ResourceManager.GetString("Script_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Script message 的本地化字符串。
        /// </summary>
        public static string Script_message {
            get {
                return ResourceManager.GetString("Script_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Script Question 的本地化字符串。
        /// </summary>
        public static string Script_Question {
            get {
                return ResourceManager.GetString("Script_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Script still runs. Save anyway?\nIt can corrupt the data file that you&apos;ll save. 的本地化字符串。
        /// </summary>
        public static string Script_still_runs__Save_anyway__nIt {
            get {
                return ResourceManager.GetString("Script_still_runs__Save_anyway__nIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Script warning 的本地化字符串。
        /// </summary>
        public static string Script_warning {
            get {
                return ResourceManager.GetString("Script_warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scripts 的本地化字符串。
        /// </summary>
        public static string Scripts {
            get {
                return ResourceManager.GetString("Scripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Scripts 的本地化字符串。
        /// </summary>
        public static string ScriptsMenu {
            get {
                return ResourceManager.GetString("ScriptsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search 的本地化字符串。
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Search in code 的本地化字符串。
        /// </summary>
        public static string Search_in_code {
            get {
                return ResourceManager.GetString("Search_in_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search in code 的本地化字符串。
        /// </summary>
        public static string Search_in_code_c1 {
            get {
                return ResourceManager.GetString("Search_in_code_c1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SepMasks 的本地化字符串。
        /// </summary>
        public static string SepMasks {
            get {
                return ResourceManager.GetString("SepMasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shader Extension Flag 的本地化字符串。
        /// </summary>
        public static string Shader_Extension_Flag {
            get {
                return ResourceManager.GetString("Shader_Extension_Flag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shader Extension Version 的本地化字符串。
        /// </summary>
        public static string Shader_Extension_Version {
            get {
                return ResourceManager.GetString("Shader_Extension_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shaders 的本地化字符串。
        /// </summary>
        public static string Shaders {
            get {
                return ResourceManager.GetString("Shaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shape 的本地化字符串。
        /// </summary>
        public static string Shape {
            get {
                return ResourceManager.GetString("Shape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Size increase 的本地化字符串。
        /// </summary>
        public static string Size_increase {
            get {
                return ResourceManager.GetString("Size_increase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Size max 的本地化字符串。
        /// </summary>
        public static string Size_max {
            get {
                return ResourceManager.GetString("Size_max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Size min 的本地化字符串。
        /// </summary>
        public static string Size_min {
            get {
                return ResourceManager.GetString("Size_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Size wiggle 的本地化字符串。
        /// </summary>
        public static string Size_wiggle {
            get {
                return ResourceManager.GetString("Size_wiggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Size 的本地化字符串。
        /// </summary>
        public static string Size1 {
            get {
                return ResourceManager.GetString("Size1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Smooth 的本地化字符串。
        /// </summary>
        public static string Smooth {
            get {
                return ResourceManager.GetString("Smooth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Solid 的本地化字符串。
        /// </summary>
        public static string Solid {
            get {
                return ResourceManager.GetString("Solid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sounds 的本地化字符串。
        /// </summary>
        public static string Sounds {
            get {
                return ResourceManager.GetString("Sounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Source position/size 的本地化字符串。
        /// </summary>
        public static string Source_position_size {
            get {
                return ResourceManager.GetString("Source_position_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Spawn on death 的本地化字符串。
        /// </summary>
        public static string Spawn_on_death {
            get {
                return ResourceManager.GetString("Spawn_on_death", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Spawn on death count 的本地化字符串。
        /// </summary>
        public static string Spawn_on_death_count {
            get {
                return ResourceManager.GetString("Spawn_on_death_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Spawn on update 的本地化字符串。
        /// </summary>
        public static string Spawn_on_update {
            get {
                return ResourceManager.GetString("Spawn_on_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Spawn on update count 的本地化字符串。
        /// </summary>
        public static string Spawn_on_update_count {
            get {
                return ResourceManager.GetString("Spawn_on_update_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Speed 的本地化字符串。
        /// </summary>
        public static string Speed {
            get {
                return ResourceManager.GetString("Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Speed increase|wiggle 的本地化字符串。
        /// </summary>
        public static string Speed_increase_wiggle {
            get {
                return ResourceManager.GetString("Speed_increase_wiggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Speed min|max 的本地化字符串。
        /// </summary>
        public static string Speed_min_max {
            get {
                return ResourceManager.GetString("Speed_min_max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sprite 的本地化字符串。
        /// </summary>
        public static string Sprite {
            get {
                return ResourceManager.GetString("Sprite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sprite frame index 的本地化字符串。
        /// </summary>
        public static string Sprite_frame_index {
            get {
                return ResourceManager.GetString("Sprite_frame_index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sprites 的本地化字符串。
        /// </summary>
        public static string Sprites {
            get {
                return ResourceManager.GetString("Sprites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start color 的本地化字符串。
        /// </summary>
        public static string Start_color {
            get {
                return ResourceManager.GetString("Start_color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Steam AppID 的本地化字符串。
        /// </summary>
        public static string Steam_AppID {
            get {
                return ResourceManager.GetString("Steam_AppID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop 的本地化字符串。
        /// </summary>
        public static string Stop1 {
            get {
                return ResourceManager.GetString("Stop1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stopping the progress bar updater task is failed.\nIt&apos;s highly recommended to restart the application. 的本地化字符串。
        /// </summary>
        public static string Stopping_the_progress_bar_updater {
            get {
                return ResourceManager.GetString("Stopping_the_progress_bar_updater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stretch sprite 的本地化字符串。
        /// </summary>
        public static string Stretch_sprite {
            get {
                return ResourceManager.GetString("Stretch_sprite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Strings 的本地化字符串。
        /// </summary>
        public static string Strings1 {
            get {
                return ResourceManager.GetString("Strings1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Subtype ID 的本地化字符串。
        /// </summary>
        public static string Subtype_ID {
            get {
                return ResourceManager.GetString("Subtype_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Switch to the next tab 的本地化字符串。
        /// </summary>
        public static string Switch_to_the_next_tab {
            get {
                return ResourceManager.GetString("Switch_to_the_next_tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Switch to the previous tab 的本地化字符串。
        /// </summary>
        public static string Switch_to_the_previous_tab {
            get {
                return ResourceManager.GetString("Switch_to_the_previous_tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Target position/size 的本地化字符串。
        /// </summary>
        public static string Target_position_size {
            get {
                return ResourceManager.GetString("Target_position_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Temp run game 的本地化字符串。
        /// </summary>
        public static string Temp_run_game {
            get {
                return ResourceManager.GetString("Temp_run_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Texture 的本地化字符串。
        /// </summary>
        public static string Texture {
            get {
                return ResourceManager.GetString("Texture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Texture Group 的本地化字符串。
        /// </summary>
        public static string Texture_Group {
            get {
                return ResourceManager.GetString("Texture_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Texture group information 的本地化字符串。
        /// </summary>
        public static string Texture_group_information {
            get {
                return ResourceManager.GetString("Texture_group_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Texture mask id 的本地化字符串。
        /// </summary>
        public static string Texture_mask_id {
            get {
                return ResourceManager.GetString("Texture_mask_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Texture page items 的本地化字符串。
        /// </summary>
        public static string Texture_page_items {
            get {
                return ResourceManager.GetString("Texture_page_items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Texture Pages 的本地化字符串。
        /// </summary>
        public static string Texture_Pages {
            get {
                return ResourceManager.GetString("Texture_Pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Textures 的本地化字符串。
        /// </summary>
        public static string Textures {
            get {
                return ResourceManager.GetString("Textures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The changes in code editor weren&apos;t saved due to some error in &quot;SaveCodeChanges()&quot;. 的本地化字符串。
        /// </summary>
        public static string The_changes_in_code_editor_weren {
            get {
                return ResourceManager.GetString("The_changes_in_code_editor_weren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The script file doesn&apos;t exist. 的本地化字符串。
        /// </summary>
        public static string The_script_file_doesn_t_exist {
            get {
                return ResourceManager.GetString("The_script_file_doesn_t_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 THINGS TO NOTE:
        ///- Keep in mind that .gml files are either not present, or will be empty. (e.g. no functions)
        ///  Because they are prebaked into GML scripts. That is completely normal. 的本地化字符串。
        /// </summary>
        public static string THINGS_TO_NOTE__n__Keep_in_mind_that {
            get {
                return ResourceManager.GetString("THINGS_TO_NOTE__n__Keep_in_mind_that", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This game contains texture(s) with unknown or unsupported image formats. These will save/load, but will not display in editors, and many operations will fail regarding them. Proceed with caution. 的本地化字符串。
        /// </summary>
        public static string This_game_contains_texture_s__with {
            get {
                return ResourceManager.GetString("This_game_contains_texture_s__with", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This game is set to run with the GameMaker Studio debugger and the normal runtime will simply hang after loading if the debugger is not running. You can turn this off in General Info by checking the &quot;Disable Debugger&quot; box and saving. 的本地化字符串。
        /// </summary>
        public static string This_game_is_set_to_run_with_the {
            get {
                return ResourceManager.GetString("This_game_is_set_to_run_with_the", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This game uses YYC (YoYo Compiler), which means the code is embedded into the game executable. This configuration is currently not fully supported; continue at your own risk. 的本地化字符串。
        /// </summary>
        public static string This_game_uses_YYC__YoYo_Compiler {
            get {
                return ResourceManager.GetString("This_game_uses_YYC__YoYo_Compiler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This is an ID (index) of the currently open asset, item, or object. It starts from 0. 的本地化字符串。
        /// </summary>
        public static string This_is_an_ID__index__of_the_currently {
            get {
                return ResourceManager.GetString("This_is_an_ID__index__of_the_currently", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This is an object reference. Drag and drop an object of matching type from the tree on the left to change it! 的本地化字符串。
        /// </summary>
        public static string This_is_an_object_reference__Drag {
            get {
                return ResourceManager.GetString("This_is_an_object_reference__Drag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This is an string reference. Change the value here to edit this just this value of all referenced values, or drag and drop another string instance from the tree on the left to change the reference 的本地化字符串。
        /// </summary>
        public static string This_is_an_string_reference__Change {
            get {
                return ResourceManager.GetString("This_is_an_string_reference__Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tile Columns 的本地化字符串。
        /// </summary>
        public static string Tile_Columns {
            get {
                return ResourceManager.GetString("Tile_Columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tile Count 的本地化字符串。
        /// </summary>
        public static string Tile_Count {
            get {
                return ResourceManager.GetString("Tile_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tile Height 的本地化字符串。
        /// </summary>
        public static string Tile_Height {
            get {
                return ResourceManager.GetString("Tile_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tile IDs 的本地化字符串。
        /// </summary>
        public static string Tile_IDs {
            get {
                return ResourceManager.GetString("Tile_IDs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tile Separation X 的本地化字符串。
        /// </summary>
        public static string Tile_Separation_X {
            get {
                return ResourceManager.GetString("Tile_Separation_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tile Separation Y 的本地化字符串。
        /// </summary>
        public static string Tile_Separation_Y {
            get {
                return ResourceManager.GetString("Tile_Separation_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tile sets 的本地化字符串。
        /// </summary>
        public static string Tile_sets {
            get {
                return ResourceManager.GetString("Tile_sets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tile Width 的本地化字符串。
        /// </summary>
        public static string Tile_Width {
            get {
                return ResourceManager.GetString("Tile_Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tilesets 的本地化字符串。
        /// </summary>
        public static string Tilesets {
            get {
                return ResourceManager.GetString("Tilesets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Timelines 的本地化字符串。
        /// </summary>
        public static string Timelines {
            get {
                return ResourceManager.GetString("Timelines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Timestamp 的本地化字符串。
        /// </summary>
        public static string Timestamp {
            get {
                return ResourceManager.GetString("Timestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TODO: The preview doesn&apos;t update live, I know, just close and reopen the object for now 的本地化字符串。
        /// </summary>
        public static string TODO__The_preview_doesn_t_update {
            get {
                return ResourceManager.GetString("TODO__The_preview_doesn_t_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Top: 的本地化字符串。
        /// </summary>
        public static string Top {
            get {
                return ResourceManager.GetString("Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transparent 的本地化字符串。
        /// </summary>
        public static string Transparent {
            get {
                return ResourceManager.GetString("Transparent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type 的本地化字符串。
        /// </summary>
        public static string Type1 {
            get {
                return ResourceManager.GetString("Type1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UndertaleModTool by krzys_h and the Underminers team\nVersion {0} 的本地化字符串。
        /// </summary>
        public static string UndertaleModTool_by_krzys_h_and_the {
            get {
                return ResourceManager.GetString("UndertaleModTool_by_krzys_h_and_the", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UndertaleModTool is already up to date.\nUpdate anyway? 的本地化字符串。
        /// </summary>
        public static string UndertaleModTool_is_already_up_to {
            get {
                return ResourceManager.GetString("UndertaleModTool_is_already_up_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UndertaleModToolUpdater app didn&apos;t exit.\nCan&apos;t delete its temp folder. 的本地化字符串。
        /// </summary>
        public static string UndertaleModToolUpdater_app_didn {
            get {
                return ResourceManager.GetString("UndertaleModToolUpdater_app_didn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown Always 2 的本地化字符串。
        /// </summary>
        public static string Unknown_Always_2 {
            get {
                return ResourceManager.GetString("Unknown_Always_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unsupported textures 的本地化字符串。
        /// </summary>
        public static string Unsupported_textures {
            get {
                return ResourceManager.GetString("Unsupported_textures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Uses physics 的本地化字符串。
        /// </summary>
        public static string Uses_physics {
            get {
                return ResourceManager.GetString("Uses_physics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Variables 的本地化字符串。
        /// </summary>
        public static string Variables {
            get {
                return ResourceManager.GetString("Variables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VarID 的本地化字符串。
        /// </summary>
        public static string VarID {
            get {
                return ResourceManager.GetString("VarID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Version 的本地化字符串。
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Vertex shader attributes 的本地化字符串。
        /// </summary>
        public static string Vertex_shader_attributes {
            get {
                return ResourceManager.GetString("Vertex_shader_attributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Visible 的本地化字符串。
        /// </summary>
        public static string Visible {
            get {
                return ResourceManager.GetString("Visible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Volume 的本地化字符串。
        /// </summary>
        public static string Volume {
            get {
                return ResourceManager.GetString("Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warning - there is another progress bar updater task running (hangs) in the background.\nRestart the application to prevent some unexpected behavior. 的本地化字符串。
        /// </summary>
        public static string Warning___there_is_another_progress {
            get {
                return ResourceManager.GetString("Warning___there_is_another_progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warning: Texture failed to load! 的本地化字符串。
        /// </summary>
        public static string Warning__Texture_failed_to_load {
            get {
                return ResourceManager.GetString("Warning__Texture_failed_to_load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warning: you currently have a project open.\nAre you sure you want to make a new project? 的本地化字符串。
        /// </summary>
        public static string Warning__you_currently_have_a_project {
            get {
                return ResourceManager.GetString("Warning__you_currently_have_a_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warnings occurred during loading. Data loss will likely occur when trying to save! 的本地化字符串。
        /// </summary>
        public static string Warnings_occurred_during_loading {
            get {
                return ResourceManager.GetString("Warnings_occurred_during_loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Welcome to UndertaleModTool! 的本地化字符串。
        /// </summary>
        public static string Welcome_to_UndertaleModTool {
            get {
                return ResourceManager.GetString("Welcome_to_UndertaleModTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Width: 的本地化字符串。
        /// </summary>
        public static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Window color 的本地化字符串。
        /// </summary>
        public static string Window_color {
            get {
                return ResourceManager.GetString("Window_color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 X 的本地化字符串。
        /// </summary>
        public static string X {
            get {
                return ResourceManager.GetString("X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Y 的本地化字符串。
        /// </summary>
        public static string Y {
            get {
                return ResourceManager.GetString("Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You are saving the game in GameMaker Studio debug mode. Unless the debugger is running, the normal runtime will simply hang after loading. You can turn this off in General Info by checking the &quot;Disable Debugger&quot; box and saving. 的本地化字符串。
        /// </summary>
        public static string You_are_saving_the_game_in_GameMaker {
            get {
                return ResourceManager.GetString("You_are_saving_the_game_in_GameMaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 YYC 的本地化字符串。
        /// </summary>
        public static string YYC {
            get {
                return ResourceManager.GetString("YYC", resourceCulture);
            }
        }
    }
}
