var coof = display_get_gui_width() / 640
var coofH = display_get_gui_height() / 480
draw_sprite_ext(spr_black, 0, 0, 0, (1 * coof), (1 * coofH), 0, c_white, black_fade)
draw_set_font(settings_font)
draw_sprite_ext(spr_controls_config, 0, (220 * coof), (22.5 * coofH), (2 * coof), (2 * coofH), 0, c_white, text_black_fade)
draw_sprite_ext(spr_button_scale, 0, (120.5 * coof), (75 * coofH), (2 * coof), (2 * coofH), 0, c_white, text_black_fade)
draw_sprite_ext(spr_arrow_leftright, 0, (459.5 * coof), (75 * coofH), (2 * coof), (2 * coofH), 0, c_white, text_black_fade)
draw_sprite_ext(spr_analog_scale, 0, (120.5 * coof), (121 * coofH), (2 * coof), (2 * coofH), 0, c_white, text_black_fade)
draw_sprite_ext(spr_arrow_leftright, 0, (459.5 * coof), (121 * coofH), (2 * coof), (2 * coofH), 0, c_white, text_black_fade)
draw_sprite_ext(spr_analog_type, 0, (124 * coof), (167 * coofH), (2 * coof), (2 * coofH), 0, c_white, text_black_fade)
draw_sprite_ext(spr_arrow_leftright, 0, (459.5 * coof), (167 * coofH), (2 * coof), (2 * coofH), 0, c_white, text_black_fade)
draw_sprite_ext(spr_controls_opacity, 0, (106.5 * coof), (213 * coofH), (2 * coof), (2 * coofH), 0, c_white, text_black_fade)
draw_sprite_ext(spr_arrow_leftright, 0, (459.5 * coof), (213 * coofH), (2 * coof), (2 * coofH), 0, c_white, text_black_fade)
draw_sprite_ext(spr_reset_config, 0, (241 * coof), (412.25 * coofH), (2 * coof), (2 * coofH), 0, c_white, text_black_fade)
draw_text_colour(settings_num_x, 67, button_scale, c_white, c_white, c_white, c_white, text_black_fade)
draw_text_colour(settings_num_x, 113, analog_scale, c_white, c_white, c_white, c_white, text_black_fade)
draw_text_colour(settings_num_x, 159, joystick_type, c_white, c_white, c_white, c_white, text_black_fade)
draw_text_colour(settings_num_x, 205, controls_opacity, c_white, c_white, c_white, c_white, text_black_fade)
draw_sprite_ext(spr_z_button, keyboard_check(ord("Z")), (zx * coof), (zy * coofH), (button_scale * coof), (button_scale * coofH), 0, c_white, controls_opacity)
draw_sprite_ext(spr_x_button, keyboard_check(ord("X")), (xx * coof), (xy * coofH), (button_scale * coof), (button_scale * coofH), 0, c_white, controls_opacity)
draw_sprite_ext(spr_c_button, keyboard_check(ord("C")), (cx * coof), (cy * coofH), (button_scale * coof), (button_scale * coofH), 0, c_white, controls_opacity)
draw_sprite_ext(spr_joybase, joystick_type, (analog_posx * coof), (analog_posy * coofH), (analog_scale * coof), (analog_scale * coofH), 0, c_white, controls_opacity)
draw_sprite_ext(spr_joystick, joystick_type, (analog_center_x * coof), (analog_center_y * coofH), (analog_scale * coof), (analog_scale * coofH), 0, c_white, controls_opacity)
draw_sprite_ext(spr_settings, keyboard_check(ord("\\")), (settingsx * coof), (settingsy * coofH), (button_scale * coof), (button_scale * coofH), 0, c_white, controls_opacity)
