var ratio = display_get_gui_width() / 640
virtual_key_zp = virtual_key_add((zx * ratio), (zy * ratio), (27 * button_scale * ratio), (29 * button_scale * ratio), 125)
virtual_key_xp = virtual_key_add((xx * ratio), (xy * ratio), (27 * button_scale * ratio), (29 * button_scale * ratio), 124)
virtual_key_cp = virtual_key_add((cx * ratio), (cy * ratio), (27 * button_scale * ratio), (29 * button_scale * ratio), 94)
virtual_key_analogp = virtual_key_add((analog_posx * ratio), (analog_posy * ratio), (59 * analog_scale * ratio), (59 * analog_scale * ratio), 93)
virtual_key_settings = virtual_key_add((settingsx * ratio), (settingsy * ratio), (19 * button_scale * ratio), (25 * button_scale * ratio), 92)
if (edit != 0)
    return;
virtual_key_z = virtual_key_add((zx * ratio), (zy * ratio), (27 * button_scale * ratio), (29 * button_scale * ratio), 90)
virtual_key_x = virtual_key_add((xx * ratio), (xy * ratio), (27 * button_scale * ratio), (29 * button_scale * ratio), 88)
virtual_key_c = virtual_key_add((cx * ratio), (cy * ratio), (27 * button_scale * ratio), (29 * button_scale * ratio), 67)
virtual_key_up = virtual_key_add((analog_posx - arrowkeys_back_area_size * analog_scale * ratio), (analog_posy - arrowkeys_back_area_size * analog_scale * ratio), (arrowkeys_back_area_size * analog_scale * ratio + (59 * analog_scale * ratio + arrowkeys_back_area_size * analog_scale * ratio)), (arrowkeys_area_size * analog_scale * ratio + arrowkeys_back_area_size * analog_scale * ratio), 38)
virtual_key_right = virtual_key_add((analog_posx + 59 * analog_scale * ratio - arrowkeys_area_size * analog_scale * ratio), (analog_posy - arrowkeys_back_area_size * analog_scale * ratio), (arrowkeys_area_size * analog_scale * ratio + arrowkeys_back_area_size * analog_scale * ratio), (arrowkeys_back_area_size * analog_scale * ratio + 59 * analog_scale * ratio + arrowkeys_back_area_size * analog_scale * ratio), 39)
virtual_key_left = virtual_key_add((analog_posx - arrowkeys_back_area_size * analog_scale * ratio), (analog_posy - arrowkeys_back_area_size * analog_scale * ratio), (arrowkeys_area_size * analog_scale * ratio + arrowkeys_back_area_size * analog_scale * ratio), (arrowkeys_back_area_size * analog_scale * ratio + (59 * analog_scale * ratio + arrowkeys_back_area_size * analog_scale * ratio)), 37)
virtual_key_down = virtual_key_add((analog_posx - arrowkeys_back_area_size * analog_scale * ratio), (analog_posy + 59 * analog_scale * ratio - arrowkeys_area_size * analog_scale * ratio), (arrowkeys_back_area_size * analog_scale * ratio + 59 * analog_scale * ratio + arrowkeys_back_area_size * analog_scale * ratio), (arrowkeys_area_size * analog_scale * ratio + arrowkeys_back_area_size * analog_scale * ratio), 40)
virtual_key_analog = virtual_key_add((analog_posx - arrowkeys_back_area_size * analog_scale * ratio), (analog_posy - arrowkeys_back_area_size * analog_scale * ratio), ((59 + arrowkeys_back_area_size) * analog_scale * ratio + arrowkeys_back_area_size * analog_scale * ratio), ((59 + arrowkeys_back_area_size) * analog_scale * ratio + arrowkeys_back_area_size * analog_scale * ratio), 126)
