var ratio = display_get_gui_width() / 640
draw_sprite_ext(spr_black, 0, 0, 0, (1 * ratio), (1 * ratio), 0, c_white, black_fade)
draw_set_font(settings_font)
draw_sprite_ext(spr_controls_config, 0, (220 * ratio), (22.5 * ratio), (2 * ratio), (2 * ratio), 0, c_white, text_black_fade)
draw_sprite_ext(spr_button_scale, 0, (120.5 * ratio), (75 * ratio), (2 * ratio), (2 * ratio), 0, c_white, text_black_fade)
draw_sprite_ext(spr_arrow_leftright, 0, (459.5 * ratio), (75 * ratio), (2 * ratio), (2 * ratio), 0, c_white, text_black_fade)
draw_sprite_ext(spr_analog_scale, 0, (120.5 * ratio), (121 * ratio), (2 * ratio), (2 * ratio), 0, c_white, text_black_fade)
draw_sprite_ext(spr_arrow_leftright, 0, (459.5 * ratio), (121 * ratio), (2 * ratio), (2 * ratio), 0, c_white, text_black_fade)
draw_sprite_ext(spr_analog_type, 0, (124 * ratio), (167 * ratio), (2 * ratio), (2 * ratio), 0, c_white, text_black_fade)
draw_sprite_ext(spr_arrow_leftright, 0, (459.5 * ratio), (167 * ratio), (2 * ratio), (2 * ratio), 0, c_white, text_black_fade)
draw_sprite_ext(spr_controls_opacity, 0, (106.5 * ratio), (213 * ratio), (2 * ratio), (2 * ratio), 0, c_white, text_black_fade)
draw_sprite_ext(spr_arrow_leftright, 0, (459.5 * ratio), (213 * ratio), (2 * ratio), (2 * ratio), 0, c_white, text_black_fade)
draw_sprite_ext(spr_reset_config, 0, (241 * ratio), (412.25 * ratio), (2 * ratio), (2 * ratio), 0, c_white, text_black_fade)
draw_text_colour(settings_num_x, 67, button_scale, c_white, c_white, c_white, c_white, text_black_fade)
draw_text_colour(settings_num_x, 113, analog_scale, c_white, c_white, c_white, c_white, text_black_fade)
draw_text_colour(settings_num_x, 159, joystick_type, c_white, c_white, c_white, c_white, text_black_fade)
draw_text_colour(settings_num_x, 205, controls_opacity, c_white, c_white, c_white, c_white, text_black_fade)
draw_sprite_ext(spr_z_button, keyboard_check(ord("Z")), (zx * ratio), (zy * ratio), (button_scale * ratio), (button_scale * ratio), 0, c_white, controls_opacity)
draw_sprite_ext(spr_x_button, keyboard_check(ord("X")), (xx * ratio), (xy * ratio), (button_scale * ratio), (button_scale * ratio), 0, c_white, controls_opacity)
draw_sprite_ext(spr_c_button, keyboard_check(ord("C")), (cx * ratio), (cy * ratio), (button_scale * ratio), (button_scale * ratio), 0, c_white, controls_opacity)
draw_sprite_ext(spr_joybase, joystick_type, (analog_posx * ratio), (analog_posy * ratio), (analog_scale * ratio), (analog_scale * ratio), 0, c_white, controls_opacity)
draw_sprite_ext(spr_joystick, joystick_type, (analog_center_x * ratio), (analog_center_y * ratio), (analog_scale * ratio), (analog_scale * ratio), 0, c_white, controls_opacity)
draw_sprite_ext(spr_settings, keyboard_check(ord("\\")), (settingsx * ratio), (settingsy * ratio), (button_scale * ratio), (button_scale * ratio), 0, c_white, controls_opacity)
