var _button_scale = lerp(1, 3, button_scale);
var _analog_scale = lerp(1, 4, analog_scale);
var _controls_opacity = lerp(0.1, 1, controls_opacity);
draw_sprite_ext(spr_black, 0, 0, 0, 1, 1, 0, c_white, lerp(0, 0.4, text_fade));
draw_sprite_ext(spr_controls_config, 0, 220, 22.5, 2, 2, 0, c_white, text_fade);
draw_sprite_ext(spr_button_scale, 0, 120.5, 75, 2, 2, 0, c_white, text_fade);
draw_sprite_ext(spr_arrow_slider, 8 * button_scale, 459.5, 75, 2, 2, 0, c_white, text_fade);
draw_sprite_ext(spr_analog_scale, 0, 120.5, 121, 2, 2, 0, c_white, text_fade);
draw_sprite_ext(spr_arrow_slider, 8 * analog_scale, 459.5, 121, 2, 2, 0, c_white, text_fade);
draw_sprite_ext(spr_analog_type, 0, 120.5, 167, 2, 2, 0, c_white, text_fade);
draw_sprite_ext(spr_arrow_switch, joystick_type, 459.5, 167, 2, 2, 0, c_white, text_fade);
draw_sprite_ext(spr_controls_opacity, 0, 120.5, 213, 2, 2, 0, c_white, text_fade);
draw_sprite_ext(spr_arrow_slider, 8 * controls_opacity, 459.5, 213, 2, 2, 0, c_white, text_fade);
draw_sprite_ext(spr_settings, keyboard_check(125), settingsx, settingsy, _button_scale, _button_scale, 0, c_white, _controls_opacity);
draw_sprite_ext(spr_z_button, keyboard_check(ord("Z")), zx, zy, _button_scale, _button_scale, 0, c_white, _controls_opacity * image_alpha);
draw_sprite_ext(spr_x_button, keyboard_check(ord("X")), xx, xy, _button_scale, _button_scale, 0, c_white, _controls_opacity * image_alpha);
draw_sprite_ext(spr_c_button, keyboard_check(ord("C")), cx, cy, _button_scale, _button_scale, 0, c_white, _controls_opacity * image_alpha);
draw_sprite_ext(spr_f1_button, keyboard_check(vk_f1), f1x, f1y, _button_scale, _button_scale, 0, c_white, _controls_opacity * image_alpha);
draw_sprite_ext(spr_joybase, joystick_type, analog_posx, analog_posy, _analog_scale, _analog_scale, 0, c_white, _controls_opacity * image_alpha);
draw_sprite_ext(spr_joystick, joystick_type, analog_center_x, analog_center_y, _analog_scale, _analog_scale, 0, c_white, _controls_opacity * image_alpha);
