//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UndertaleModTool.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UndertaleModTool.Resources.Languages.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   UndertaleModTool by krzys_h v: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string App_Title_Main {
            get {
                return ResourceManager.GetString("App_Title_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No game loaded に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string App_Title_NoGameLoaded {
            get {
                return ResourceManager.GetString("App_Title_NoGameLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_File {
            get {
                return ResourceManager.GetString("Menu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Close に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_File_Close {
            get {
                return ResourceManager.GetString("Menu_File_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Generate o_ffset map に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_File_GenerateOffsetMap {
            get {
                return ResourceManager.GetString("Menu_File_GenerateOffsetMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _New に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_File_New {
            get {
                return ResourceManager.GetString("Menu_File_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Open に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_File_Open {
            get {
                return ResourceManager.GetString("Menu_File_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Run game under GMS _debugger に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_File_RunGameUnderGMSDebugger {
            get {
                return ResourceManager.GetString("Menu_File_RunGameUnderGMSDebugger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Run game with other runner に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_File_RunGameWithOtherRunner {
            get {
                return ResourceManager.GetString("Menu_File_RunGameWithOtherRunner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Save に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_File_Save {
            get {
                return ResourceManager.GetString("Menu_File_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   S_ettings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_File_Settings {
            get {
                return ResourceManager.GetString("Menu_File_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Temp run game に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_File_TempRunGame {
            get {
                return ResourceManager.GetString("Menu_File_TempRunGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Find に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_Find {
            get {
                return ResourceManager.GetString("Menu_Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Find unreferenced _assets に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_Find_FindUnreferencedAssets {
            get {
                return ResourceManager.GetString("Menu_Find_FindUnreferencedAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Search in code に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_Find_SearchInCode {
            get {
                return ResourceManager.GetString("Menu_Find_SearchInCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Help に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_Help {
            get {
                return ResourceManager.GetString("Menu_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _About に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_Help_About {
            get {
                return ResourceManager.GetString("Menu_Help_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _GitHub に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_Help_GitHub {
            get {
                return ResourceManager.GetString("Menu_Help_GitHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Scripts に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_Scripts {
            get {
                return ResourceManager.GetString("Menu_Scripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (...loading...) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_Scripts_Loading {
            get {
                return ResourceManager.GetString("Menu_Scripts_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open a data.win file to get started, then double click on the items on the left to view them. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_GetStarted {
            get {
                return ResourceManager.GetString("Msg_GetStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Load data.win file first に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_LoadDataWinFileFirst {
            get {
                return ResourceManager.GetString("Msg_LoadDataWinFileFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Welcome to UndertaleModTool! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_Welcome {
            get {
                return ResourceManager.GetString("Msg_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Audio groups に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tree_AudioGroups {
            get {
                return ResourceManager.GetString("Tree_AudioGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Backgrounds &amp;amp; Tile sets に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tree_BackgroundsAndTileSets {
            get {
                return ResourceManager.GetString("Tree_BackgroundsAndTileSets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Code に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tree_Code {
            get {
                return ResourceManager.GetString("Tree_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Code locals に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tree_CodeLocals {
            get {
                return ResourceManager.GetString("Tree_CodeLocals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Data に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tree_Data {
            get {
                return ResourceManager.GetString("Tree_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Embedded audio に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tree_EmbeddedAudio {
            get {
                return ResourceManager.GetString("Tree_EmbeddedAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Embedded images に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tree_EmbeddedImages {
            get {
                return ResourceManager.GetString("Tree_EmbeddedImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Embedded textures に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tree_EmbeddedTextures {
            get {
                return ResourceManager.GetString("Tree_EmbeddedTextures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Extensions に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tree_Extensions {
            get {
                return ResourceManager.GetString("Tree_Extensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Filter by name... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tree_FilterByName {
            get {
                return ResourceManager.GetString("Tree_FilterByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fonts に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tree_Fonts {
            get {
                return ResourceManager.GetString("Tree_Fonts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Functions に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tree_Functions {
            get {
                return ResourceManager.GetString("Tree_Functions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Game End scripts に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tree_GameEndScript {
            get {
                return ResourceManager.GetString("Tree_GameEndScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Game objects に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tree_GameObjects {
            get {
                return ResourceManager.GetString("Tree_GameObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   General info に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tree_GeneralInfo {
            get {
                return ResourceManager.GetString("Tree_GeneralInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Global init に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tree_GlobalInit {
            get {
                return ResourceManager.GetString("Tree_GlobalInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Particle system emitters に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tree_ParticleSystemEmitters {
            get {
                return ResourceManager.GetString("Tree_ParticleSystemEmitters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Particle systems に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tree_ParticleSystems {
            get {
                return ResourceManager.GetString("Tree_ParticleSystems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Paths に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tree_Paths {
            get {
                return ResourceManager.GetString("Tree_Paths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rooms に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tree_Rooms {
            get {
                return ResourceManager.GetString("Tree_Rooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scripts に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tree_Scripts {
            get {
                return ResourceManager.GetString("Tree_Scripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shaders に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tree_Shaders {
            get {
                return ResourceManager.GetString("Tree_Shaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sounds に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tree_Sounds {
            get {
                return ResourceManager.GetString("Tree_Sounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sprites に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tree_Sprites {
            get {
                return ResourceManager.GetString("Tree_Sprites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Strings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tree_Strings {
            get {
                return ResourceManager.GetString("Tree_Strings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Texture group infomation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tree_TextureGroupInfomation {
            get {
                return ResourceManager.GetString("Tree_TextureGroupInfomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Texture page items に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tree_TexturePageItems {
            get {
                return ResourceManager.GetString("Tree_TexturePageItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Timelines に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tree_Timelines {
            get {
                return ResourceManager.GetString("Tree_Timelines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Variables に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tree_Variables {
            get {
                return ResourceManager.GetString("Tree_Variables", resourceCulture);
            }
        }
    }
}
