//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UndertaleModTool.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UndertaleModTool.Resources.Languages.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   UndertaleModTool by krzys_h v: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string App_Title_Main {
            get {
                return ResourceManager.GetString("App_Title_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No game loaded に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string App_Title_NoGameLoaded {
            get {
                return ResourceManager.GetString("App_Title_NoGameLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AudioGroup_Name {
            get {
                return ResourceManager.GetString("AudioGroup_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Path (GM 2024.14+) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AudioGroup_Path {
            get {
                return ResourceManager.GetString("AudioGroup_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Export に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EAudio_Export {
            get {
                return ResourceManager.GetString("EAudio_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Import に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EAudio_Import {
            get {
                return ResourceManager.GetString("EAudio_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Play に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EAudio_Play {
            get {
                return ResourceManager.GetString("EAudio_Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stop に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EAudio_Stop {
            get {
                return ResourceManager.GetString("EAudio_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   WAV data, length: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EAudio_WAVDataLength {
            get {
                return ResourceManager.GetString("EAudio_WAVDataLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EImage_Name {
            get {
                return ResourceManager.GetString("EImage_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Texture に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EImage_Texture {
            get {
                return ResourceManager.GetString("EImage_Texture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_File {
            get {
                return ResourceManager.GetString("Menu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Close に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_File_Close {
            get {
                return ResourceManager.GetString("Menu_File_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Generate o_ffset map に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_File_GenerateOffsetMap {
            get {
                return ResourceManager.GetString("Menu_File_GenerateOffsetMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _New に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_File_New {
            get {
                return ResourceManager.GetString("Menu_File_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Open に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_File_Open {
            get {
                return ResourceManager.GetString("Menu_File_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Run game under GMS _debugger に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_File_RunGameUnderGMSDebugger {
            get {
                return ResourceManager.GetString("Menu_File_RunGameUnderGMSDebugger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Run game with other runner に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_File_RunGameWithOtherRunner {
            get {
                return ResourceManager.GetString("Menu_File_RunGameWithOtherRunner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Save に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_File_Save {
            get {
                return ResourceManager.GetString("Menu_File_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   S_ettings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_File_Settings {
            get {
                return ResourceManager.GetString("Menu_File_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Temp run game に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_File_TempRunGame {
            get {
                return ResourceManager.GetString("Menu_File_TempRunGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Find に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_Find {
            get {
                return ResourceManager.GetString("Menu_Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Find unreferenced _assets に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_Find_FindUnreferencedAssets {
            get {
                return ResourceManager.GetString("Menu_Find_FindUnreferencedAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Search in code に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_Find_SearchInCode {
            get {
                return ResourceManager.GetString("Menu_Find_SearchInCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Help に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_Help {
            get {
                return ResourceManager.GetString("Menu_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _About に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_Help_About {
            get {
                return ResourceManager.GetString("Menu_Help_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _GitHub に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_Help_GitHub {
            get {
                return ResourceManager.GetString("Menu_Help_GitHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Scripts に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_Scripts {
            get {
                return ResourceManager.GetString("Menu_Scripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (...loading...) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_Scripts_Loading {
            get {
                return ResourceManager.GetString("Menu_Scripts_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Run _other script... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_Scripts_RunOtherScript {
            get {
                return ResourceManager.GetString("Menu_Scripts_RunOtherScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UndertaleModTool by krzys_h and the Underminers team
        ///Version  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_About {
            get {
                return ResourceManager.GetString("Msg_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Warning: you currently have a project open.
        ///Are you sure you want to make a new project? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_AreYouSureYouWantToMakeANewProject {
            get {
                return ResourceManager.GetString("Msg_AreYouSureYouWantToMakeANewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Double click on the items on the left to view them に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_DoubleClick {
            get {
                return ResourceManager.GetString("Msg_DoubleClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Expand the list on the left to edit items に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_ExpandList {
            get {
                return ResourceManager.GetString("Msg_ExpandList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open a data.win file to get started, then double click on the items on the left to view them. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_GetStarted {
            get {
                return ResourceManager.GetString("Msg_GetStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New file created, have fun making a game out of nothing
        ///I TOLD YOU to open a data.win, not create a new file! :P に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_GetStartedFromEmpty {
            get {
                return ResourceManager.GetString("Msg_GetStartedFromEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Load data.win file first に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_LoadDataWinFileFirst {
            get {
                return ResourceManager.GetString("Msg_LoadDataWinFileFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Loading, please wait... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_LoadingPleaseWait {
            get {
                return ResourceManager.GetString("Msg_LoadingPleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Loading に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_LoadingTitle {
            get {
                return ResourceManager.GetString("Msg_LoadingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open data.win file to get started に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_OpenDataToStart {
            get {
                return ResourceManager.GetString("Msg_OpenDataToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please wait... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_PleaseWait {
            get {
                return ResourceManager.GetString("Msg_PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save changes before quitting? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_SaveChangesBeforeQuitting {
            get {
                return ResourceManager.GetString("Msg_SaveChangesBeforeQuitting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Saving, please wait... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_SavingPleaseWait {
            get {
                return ResourceManager.GetString("Msg_SavingPleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Saving に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_SavingTitle {
            get {
                return ResourceManager.GetString("Msg_SavingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Temp folder is null. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_TempFolderIsNull {
            get {
                return ResourceManager.GetString("Msg_TempFolderIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot find game executable path, expected:  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_TempRunCannotFindExecutable {
            get {
                return ResourceManager.GetString("Msg_TempRunCannotFindExecutable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot find game path, expected:  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_TempRunCannotFindGamePath {
            get {
                return ResourceManager.GetString("Msg_TempRunCannotFindGamePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Nothing to run! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_TempRunNothingToRun {
            get {
                return ResourceManager.GetString("Msg_TempRunNothingToRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Null game executable name or location に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_TempRunNull {
            get {
                return ResourceManager.GetString("Msg_TempRunNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Temp save failed, cannot run. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_TempRunSaveFailed {
            get {
                return ResourceManager.GetString("Msg_TempRunSaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   WARNING:
        ///Temp running the game does not permanently 
        ///save your changes. Please &quot;Save&quot; the game
        ///to save your changes. Closing UndertaleModTool
        ///without using the &quot;Save&quot; option can
        ///result in loss of work. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_TempRunWarn {
            get {
                return ResourceManager.GetString("Msg_TempRunWarn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Welcome to UndertaleModTool! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_Welcome {
            get {
                return ResourceManager.GetString("Msg_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save as PNG に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RoomEditor_SaveAsPng {
            get {
                return ResourceManager.GetString("RoomEditor_SaveAsPng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Audio file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Sound_AudioFile {
            get {
                return ResourceManager.GetString("Sound_AudioFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Audio group に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Sound_AudioGroup {
            get {
                return ResourceManager.GetString("Sound_AudioGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Effects に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Sound_Effects {
            get {
                return ResourceManager.GetString("Sound_Effects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Sound_File {
            get {
                return ResourceManager.GetString("Sound_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Flags に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Sound_Flags {
            get {
                return ResourceManager.GetString("Sound_Flags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Sound_Name {
            get {
                return ResourceManager.GetString("Sound_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pitch に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Sound_Pitch {
            get {
                return ResourceManager.GetString("Sound_Pitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Play に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Sound_Play {
            get {
                return ResourceManager.GetString("Sound_Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Preload (old audio system) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Sound_Preload {
            get {
                return ResourceManager.GetString("Sound_Preload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stop に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Sound_Stop {
            get {
                return ResourceManager.GetString("Sound_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Sound_Type {
            get {
                return ResourceManager.GetString("Sound_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Volume に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Sound_Volume {
            get {
                return ResourceManager.GetString("Sound_Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bounding box mode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Sprite_BoundingBoxMode {
            get {
                return ResourceManager.GetString("Sprite_BoundingBoxMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Collision masks に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Sprite_CollisionMasks {
            get {
                return ResourceManager.GetString("Sprite_CollisionMasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Double click to add に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Sprite_DoubleClickToAdd {
            get {
                return ResourceManager.GetString("Sprite_DoubleClickToAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Export all frames (or Spine data if this is a Spine sprite) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Sprite_ExportAllFrames {
            get {
                return ResourceManager.GetString("Sprite_ExportAllFrames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Is special type? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Sprite_IsSpecialType {
            get {
                return ResourceManager.GetString("Sprite_IsSpecialType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Margin Left/Right/Bottom/Top に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Sprite_Margin {
            get {
                return ResourceManager.GetString("Sprite_Margin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Sprite_Name {
            get {
                return ResourceManager.GetString("Sprite_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Origin に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Sprite_Origin {
            get {
                return ResourceManager.GetString("Sprite_Origin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Playback speed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Sprite_PlaybackSpeed {
            get {
                return ResourceManager.GetString("Sprite_PlaybackSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Playback speed type に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Sprite_PlaybackSpeedType {
            get {
                return ResourceManager.GetString("Sprite_PlaybackSpeedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Preload に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Sprite_Preload {
            get {
                return ResourceManager.GetString("Sprite_Preload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SepMasks に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Sprite_SepMasks {
            get {
                return ResourceManager.GetString("Sprite_SepMasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Size に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Sprite_Size {
            get {
                return ResourceManager.GetString("Sprite_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Smooth に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Sprite_Smooth {
            get {
                return ResourceManager.GetString("Sprite_Smooth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Textures に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Sprite_Textures {
            get {
                return ResourceManager.GetString("Sprite_Textures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Transparent に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Sprite_Transparent {
            get {
                return ResourceManager.GetString("Sprite_Transparent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Sprite_Type {
            get {
                return ResourceManager.GetString("Sprite_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Version に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Sprite_Version {
            get {
                return ResourceManager.GetString("Sprite_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Audio Group に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tabs_AudioGroup {
            get {
                return ResourceManager.GetString("Tabs_AudioGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Embedded Audio に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tabs_EmbeddedAudio {
            get {
                return ResourceManager.GetString("Tabs_EmbeddedAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Embedded Image に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tabs_EmbeddedImage {
            get {
                return ResourceManager.GetString("Tabs_EmbeddedImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sound に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tabs_Sound {
            get {
                return ResourceManager.GetString("Tabs_Sound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sprite に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tabs_Sprite {
            get {
                return ResourceManager.GetString("Tabs_Sprite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Audio groups に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tree_AudioGroups {
            get {
                return ResourceManager.GetString("Tree_AudioGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Backgrounds &amp; Tile sets に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tree_BackgroundsAndTileSets {
            get {
                return ResourceManager.GetString("Tree_BackgroundsAndTileSets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Code に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tree_Code {
            get {
                return ResourceManager.GetString("Tree_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Code locals に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tree_CodeLocals {
            get {
                return ResourceManager.GetString("Tree_CodeLocals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Data に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tree_Data {
            get {
                return ResourceManager.GetString("Tree_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Embedded audio に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tree_EmbeddedAudio {
            get {
                return ResourceManager.GetString("Tree_EmbeddedAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Embedded images に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tree_EmbeddedImages {
            get {
                return ResourceManager.GetString("Tree_EmbeddedImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Embedded textures に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tree_EmbeddedTextures {
            get {
                return ResourceManager.GetString("Tree_EmbeddedTextures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Extensions に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tree_Extensions {
            get {
                return ResourceManager.GetString("Tree_Extensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Filter by name... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tree_FilterByName {
            get {
                return ResourceManager.GetString("Tree_FilterByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fonts に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tree_Fonts {
            get {
                return ResourceManager.GetString("Tree_Fonts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Functions に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tree_Functions {
            get {
                return ResourceManager.GetString("Tree_Functions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Game End scripts に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tree_GameEndScript {
            get {
                return ResourceManager.GetString("Tree_GameEndScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Game objects に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tree_GameObjects {
            get {
                return ResourceManager.GetString("Tree_GameObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   General info に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tree_GeneralInfo {
            get {
                return ResourceManager.GetString("Tree_GeneralInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Global init に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tree_GlobalInit {
            get {
                return ResourceManager.GetString("Tree_GlobalInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Particle system emitters に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tree_ParticleSystemEmitters {
            get {
                return ResourceManager.GetString("Tree_ParticleSystemEmitters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Particle systems に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tree_ParticleSystems {
            get {
                return ResourceManager.GetString("Tree_ParticleSystems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Paths に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tree_Paths {
            get {
                return ResourceManager.GetString("Tree_Paths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rooms に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tree_Rooms {
            get {
                return ResourceManager.GetString("Tree_Rooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scripts に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tree_Scripts {
            get {
                return ResourceManager.GetString("Tree_Scripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shaders に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tree_Shaders {
            get {
                return ResourceManager.GetString("Tree_Shaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sounds に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tree_Sounds {
            get {
                return ResourceManager.GetString("Tree_Sounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sprites に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tree_Sprites {
            get {
                return ResourceManager.GetString("Tree_Sprites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Strings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tree_Strings {
            get {
                return ResourceManager.GetString("Tree_Strings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Texture group infomation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tree_TextureGroupInfomation {
            get {
                return ResourceManager.GetString("Tree_TextureGroupInfomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Texture page items に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tree_TexturePageItems {
            get {
                return ResourceManager.GetString("Tree_TexturePageItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tile sets に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tree_TileSets {
            get {
                return ResourceManager.GetString("Tree_TileSets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Timelines に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tree_Timelines {
            get {
                return ResourceManager.GetString("Tree_Timelines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Variables に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tree_Variables {
            get {
                return ResourceManager.GetString("Tree_Variables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   About に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Window_About {
            get {
                return ResourceManager.GetString("Window_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Window_Error {
            get {
                return ResourceManager.GetString("Window_Error", resourceCulture);
            }
        }
    }
}
