name: Publish CI release

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    with:
      gui-bundled-config: "[ true ]"
      cli-bundled-config: "[ true ]"

  publish:
    name: Publish
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - id: get-short-rev
      run: echo "::set-output name=short_rev::$(git rev-parse --short HEAD)"

    - name: Prepare GUI-win-x64-bundled
      uses: ./.github/actions/download-and-zip-artifact
      with:
        name: GUI-win-x64-bundled

    - name: Prepare GUI-win-x64-bundled-singleFile
      uses: ./.github/actions/download-and-zip-artifact
      with:
        name: GUI-win-x64-bundled-singleFile

    - name: Prepare CLI-win-x64-bundled
      uses: ./.github/actions/download-and-zip-artifact
      with:
        name: CLI-win-x64-bundled

    - name: Prepare CLI-osx-x64-bundled
      uses: ./.github/actions/download-and-zip-artifact
      with:
        name: CLI-osx-x64-bundled

    - name: Prepare CLI-linux-x64-bundled
      uses: ./.github/actions/download-and-zip-artifact
      with:
        name: CLI-linux-x64-bundled

    - name: Update release
      uses: IsaacShelton/update-existing-release@v1.3.1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        files: >
          GUI-win-x64-bundled.zip
          GUI-win-x64-bundled-singleFile.zip
          CLI-win-x64-bundled.zip
          CLI-osx-x64-bundled.zip
          CLI-linux-x64-bundled.zip
        release: Bleeding Edge
        tag: bleeding-edge
        body: |
          This is an automatically updating **bleeding edge** build of UndertaleModTool. There *will* be bugs!
          If you encounter any, please make an issue on GitHub or join the Underminers Discord for more help!
        prerelease: false
