name: Publish UndertaleModToolAvalonia

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_gui:

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        configuration: [Release]
        bundled: [true]
        singlefile: [false]
        include:
          - os: ubuntu-latest
            rid: linux-x64
          - os: macOS-latest
            rid: osx-x64
          - os: windows-latest
            rid: win-x64

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Publish ${{ matrix.os }} GUI
      run: |
        dotnet publish UndertaleModToolAvalonia.Desktop -c ${{ matrix.configuration }} -r ${{ matrix.rid }} --self-contained ${{ matrix.bundled }} -p:PublishSingleFile=${{ matrix.singlefile }} --output Publish/${{ matrix.os }}
    - name: Copy external files
      run: |
        cp ./README.md ./Publish/${{ matrix.os }}
        cp ./SCRIPTS.md ./Publish/${{ matrix.os }}
        cp ./LICENSE.txt ./Publish/${{ matrix.os }}
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
          name: GUI-${{ matrix.os }}-${{ matrix.configuration }}-isBundled-${{ matrix.bundled }}-isSingleFile-${{ matrix.singlefile }}
          path: Publish/${{ matrix.os }}
